In [1]:
import numpy as np
import pandas as pd

In [4]:
flats = pd.read_csv('data_csv/flats_cleaned.csv')
houses = pd.read_csv('data_csv/house_cleaned.csv')

In [5]:
df = pd.concat([flats,houses],ignore_index=True)

In [6]:
df = df.sample(df.shape[0],ignore_index=True)

In [7]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 99A Gurgaon,flat,pareena coban residences,1.45,7260.0,1997.0,Super Built up area 1997(185.53 sq.m.),3,5,3,"servant room,others","Sector 99A Gurgaon, Gurgaon, Haryana",11.0,NaN,1 to 5 Year Old,"['Gopal Super Market', 'Little Need Super Mark...","3 bhk unit comes with 5 toilets, servent room,...","['3 Fan', '1 Exhaust Fan', '5 Light', '5 AC', ...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle3 out of 5..."
1,3 BHK Flat in Sector 67A Gurgaon,flat,ireo the corridors,1.70,9843.0,1727.0,Super Built up area 1727(160.44 sq.m.)Carpet a...,3,3,2,"servant room,others","Sector 67A Gurgaon, Gurgaon, Haryana",10.0,North-East,0 to 1 Year Old,"['Huda Metro Station (Gurugram)', 'Paras Trini...",This 3 bhk flat is located in ireo the corrido...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Intercom Facility',...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2,1 BHK Flat in Sector 40 Gurgaon,flat,lig flat,1.50,50000.0,300.0,Built Up area: 300 (27.87 sq.m.),1,1,0,not available,"Lig Flat, Sector 40, Gurgaon, Sector 40 Gurgao...",0.0,NaN,undefined,"['Huda city centre metro station', 'Axis bank ...",Looking for a 1 bhk apartment for sale in gurg...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3,4 BHK Flat in Sector 37D Gurgaon,flat,bptp terra,1.75,7987.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,4,3,others,"702, Sector 37D Gurgaon, Gurgaon, Haryana",7.0,West,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...",Location advantages: Situated close to propos...,"['1 Wardrobe', '1 Stove', '5 Light', '6 AC', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction4.5 ou..."
4,1 BHK Flat in Sector 56 Gurgaon,flat,kendriya vihar,0.47,7768.0,605.0,Carpet area: 605 (56.21 sq.m.),1,1,1,not available,"Sector 56 Gurgaon, Gurgaon, Haryana",3.0,NaN,10+ Year Old,"['Sector metro station', 'Sector metro station...",1 bhk property in a well maintained gated soci...,"['1 Wardrobe', '1 Bed', '1 Water Purifier', '2...","['Power Back-up', 'Maintenance Staff', 'Water ...","['Green Area5 out of 5', 'Construction4 out of..."

In [9]:
df.to_csv('data_csv/gurgaon_properties.csv',index=False)